### PR TITLE
Fix #1187: User tasks endpoint returns error for CompletedWithError tasks when fetch_complete_task=true

### LINKED ISSUE #1187: User tasks request fails if any task is CompletedWithError and fetch_completed_tasks=true
Currently the `/user_tasks` endpoint will give a 500 error response if any task is CompletedWithoutError and the request includes `fetch_completed_tasks=true`. This prevents the user from seeing if a task is CompletedWithError as all you get is an error.

This happens if you requests a specific task with `user_task_ids=.....` or if you just ask for all tasks to be listed.

The offending code is the `getJsonStructure` method in: `cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java`.

A possible fix is for tasks with `status == CompletedWithError` to not throw an exception and just return "error" in their `ORIGINAL_RESPONSE` field.

### PR DESCRIPTION
**Pull request by tomncooper**
Addresses issue #1187, where the user tasks endpoint returns an error if a task `CompletedWithError` and `fetch_complete_task=true` is in the request. This prevents the user from learning the state of these tasks.

This changes the `getJSonStructure` method to not throw an error for `CompletedWithError` tasks when `fetch_complete_task=true` and instead just return `"CompletedWithError"` in the `originalResponse` field.

### CODE REVIEW

**Comment by tomncooper** [comment]
So checkstyle failed, but the line it is complaining about doesn't exit? How do I run the checkstyle task locally?

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java [hunk 1]
```diff
@@ -763,9 +763,16 @@ private void logOperation() {
       // Populate original response of completed task if requested so.
       if (fetchCompletedTask) {
         try {
+          // TODO: For CompletedWithError tasks the cached response should contain the original server side error information
           jsonObjectMap.put(ORIGINAL_RESPONSE, lastFuture().get().cachedResponse());
         } catch (InterruptedException | ExecutionException e) {
-          throw new IllegalStateException("Error happened in fetching response for task " + _userTaskId.toString(), e);
+          if (_state == TaskState.COMPLETED_WITH_ERROR){
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java:769]: > So checkstyle failed, but the line it is complaining about doesn't exit? How do I run the checkstyle task locally?

@tomncooper This is due to a missing space before `{` in this line:
```
> Task :cruise-control:checkstyleMain
[ant:checkstyle] [ERROR] /home/circleci/workspace/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java:769:56: '{' is not preceded with whitespace. [WhitespaceAround]
```

File: docs/wiki/User Guide/REST-APIs.md [hunk 2]
```diff
@@ -231,7 +231,7 @@ Supported parameters are:
 
 User can use `user_task_ids`/`client_ids`/`endpoints`/`types` make Cruise Control only return requests they are interested. By default all the requests get returned.
 
-If `fetch_completed_task` is set to `true`, the original response of each requests will be returned.
+If `fetch_completed_task` is set to `true`, the original response of each requests will be returned. In the case where a task completed with errors the response will be `"CompletedWithError"`.
```
Comment (efeg) [inline docs/wiki/User Guide/REST-APIs.md:234]: Nit: Double quotes (i.e. `"`) seems redundant since `CompletedWithError ` is already inside backticks.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java (hunk 1 above)
Comment (tomncooper) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java:769]: Great, thanks.

File: docs/wiki/User Guide/REST-APIs.md (hunk 2 above)
Comment (tomncooper) [reply docs/wiki/User Guide/REST-APIs.md]: Good point.

**Comment by tomncooper** [comment]
Thanks for the comment @efeg. Hopefully this is good to merge now.
