### PR TITLE
Make sure the provision response is always RIGHT_SIZED if it is not OVER_PROVISIONED

### LINKED ISSUE #1877: Cruise-control falsely report OVER_PROVISIONED when the cluster is right_sized
There are multiple goals in cruise-control that could provide OVER_PROVISIONED as the ProvisionStatus. After all goals are optimized, there will be an aggregated ProvisionStatus. 

It is expected that the aggregated ProvisionStatus is OVER_PROVISIONED if and only if ALL relative goals provide OVER_PROVISIONED status.

Today there is a bug in cruise-control that violates the above rule. For example:

For ReplicaDistributionGoal,  even if this goal decides the cluster is NOT OVER_PROVISIONED, the final aggregated provision response could still be OVER_PROVISIONED. This happens when ReplicaDistributionGoal fails and returns an UNDECIDED provision status.

As a fix, we should make sure that all the goals that can possibly returns OVER_PROVISIONED, will never returns UNDECIDED as provision status. These goals include:

- BrokerSetAwareGoal
- RackAwareDistributionGoal
- RackAwareGoal
- ReplicaDistributionGoal
- ResourceDistributionGoal

### PR DESCRIPTION
**Pull request by CCisGG**
This PR resolves #1877 .

### CODE REVIEW

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java [hunk 1]
```diff
@@ -236,6 +234,7 @@ protected void rebalanceForBroker(Broker broker, ClusterModel clusterModel, Set<
                                                        .collect(Collectors.toSet());
       if (maybeApplyBalancingAction(clusterModel, replica, eligibleBrokers, ActionType.INTER_BROKER_REPLICA_MOVEMENT, optimizedGoals,
                                     optimizationOptions) == null) {
+        _provisionResponse = new ProvisionResponse(ProvisionStatus.UNDER_PROVISIONED);
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java:237]: Why do we need this? Isn't this handled in `AbstractGoal#optimize`?

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java [hunk 2]
```diff
@@ -161,6 +161,7 @@ protected void initGoalState(ClusterModel clusterModel, OptimizationOptions opti
     _brokerSetResolutionHelper = new BrokerSetResolutionHelper(clusterModel, brokerSetResolver);
     _brokersByBrokerSet = _brokerSetResolutionHelper.brokersByBrokerSetId();
     _replicaToBrokerSetMappingPolicy = _balancingConstraint.replicaToBrokerSetMappingPolicy();
+    _provisionResponse = new ProvisionResponse(ProvisionStatus.RIGHT_SIZED);
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java:164]: Why do we set this to right sized? Wouldn't this cause the cluster never being reported as over provisioned if this goal is used?

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java [hunk 3]
```diff
@@ -101,8 +101,7 @@ protected void updateGoalState(ClusterModel clusterModel, OptimizationOptions op
       ProvisionRecommendation recommendation = new ProvisionRecommendation.Builder(ProvisionStatus.OVER_PROVISIONED)
           .numBrokers(numBrokersToDrop).build();
       _provisionResponse = new ProvisionResponse(ProvisionStatus.OVER_PROVISIONED, recommendation, name());
-    } else if (_succeeded) {
-      // The cluster is not overprovisioned and all brokers are within the upper and lower balance limits.
+    } else {
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java:104]: Did we check the other goals, which set the _provisionResponse to `OVER_PROVISIONED` for the same bug?

**Review by efeg — CHANGES_REQUESTED** [review]

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java (hunk 3 above)
Comment (CCisGG) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java:104]: Yes, others will not have the same issue.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java (hunk 2 above)
Comment (CCisGG) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java:164]: I guess you're right. I'll remove this line. However this does cause confusion to me, and maybe to following developers. Essentially you don't return RIGHT_SIZED even if your goal proves the cluster is neither OVER_PROVISIONED nor UNDER_PROVISIONED. I think it is confusing.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java (hunk 1 above)
Comment (CCisGG) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java:237]: Got it. I just noticed it.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java [hunk 4]
```diff
@@ -234,7 +232,6 @@ protected void rebalanceForBroker(Broker broker, ClusterModel clusterModel, Set<
                                                        .collect(Collectors.toSet());
       if (maybeApplyBalancingAction(clusterModel, replica, eligibleBrokers, ActionType.INTER_BROKER_REPLICA_MOVEMENT, optimizedGoals,
                                     optimizationOptions) == null) {
-        _provisionResponse = new ProvisionResponse(ProvisionStatus.UNDER_PROVISIONED);
```
Comment (mohitpali) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java]: I dont fully understand. If a brokerSetAware goal is violated and can not be fixed, the recommendation provided by BrokerSetAwareGoal would be UNDER_PROVISIONED, since we would need to add more brokers to the brokerSet. There could be other brokerSets that do not need to add any additional brokers.

Comment (efeg) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java]: @mohitpali Yes, it is going to be `UNDER_PROVISIONED`. Please check out how `AbstractGoal#optimize` handles `OptimizationFailureException` -- note that `BrokerSetAwareGoal` extends `AbstractGoal`.

**Review by efeg — APPROVED** [review]
Thanks for the updates - LGTM.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java (hunk 2 above)
Comment (efeg) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java]: For a goal to indicate whether a cluster is right sized, it must be able to gauge whether the cluster is over provisioned or not. Since the current implementation of this goal has no criteria to say whether the cluster is over provisioned or not, it cannot claim the cluster as right sized.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java (hunk 4 above)
Comment (mohitpali) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java]: Ok, makes sense.
