### PR TITLE
Convert traditional null checks to use Utils.validateNotNull

### LINKED ISSUE #1387: Convert traditional null checks to use Objects.requireNonNull
The current codebase uses traditional null checks:
```
    if (object == null) {
        throw new IllegalArgumentException("object cannot be null!");
    }
```

Adopt the following whenever appropriate, which would make the code easier to read:
```
  public static <T> T validateNotNull(T obj, String objName) {
    Objects.requireNonNull(obj, objName + " cannot be null.");
    return obj;
  }
```

### PR DESCRIPTION
**Pull request by aminburhan**
This PR resolves #1387.

### CODE REVIEW

**Review by Lincong — CHANGES_REQUESTED** [review]
Thanks for the PR. How about considering adding the below static methods to the `Utils` class.

```
  public static <T> T validateNotNull(T obj, String errorMsg) {
    Objects.requireNonNull(obj, errorMsg);
    return obj;
  }

  public static <T> T validateNotNull(T obj, Supplier<String> errorMsgSupplier) {
    Objects.requireNonNull(obj, errorMsgSupplier.get());
    return obj;
  }
```

With the above two methods, we can do:

```
Utils.validateNotNull(someObj, "Hey! This object cannot be null");
```
or with lazy evaluation
```
Utils.validateNotNull(someObj, () -> "This error message is generated only when the exception needs to be thrown");
```

Another thing to note is that I think there are more cases that can be replaced with the above methods. I tried to search `cannot be null` in the codebase.

Let me know your opinions. Thanks!

**Comment by aminburhan** [comment]
Thanks for your feedback. My apologies for misunderstanding the issue description, where it's clearly stated that a static method should be adopted. 

I agree with your suggested changes, which will make the code easier to read.  I'll implement the changes  and see if there's more cases that can be replaced. Thanks!

**Comment by Lincong** [comment]
> Thanks for your feedback. My apologies for misunderstanding the issue description, where it's clearly stated that a static method should be adopted.
> 
> I agree with your suggested changes, which will make the code easier to read. I'll implement the changes and see if there's more cases that can be replaced. Thanks!

Thanks. Another thing to note is that most null check currently throws `IllegalArguementException`. When we start using `Objects.requireNotNull()`, it throws `NullPointException` instead. In theory, if there's any logic that catches `IllegalArguementException` and handles it in some ways, that logic will not work with `NullPointException` anymore since it does not catch it. It's very rare (I personally have not seen any) to try and catch `IllegalArguementException`. Still want to point it out.

**Comment by aminburhan** [comment]
The previous traditional null checks before change throws an `IllegalArgumentExpection` if the checked object reference is null.

```
    if (object == null) {
        throw new IllegalArgumentException("object cannot be null!");
    }
```

However the `Objects.requireNonNull` throws a `NullPointerException`.  In order not to break any previous code, in case there are tests that expects an `IllegalArgumentException` to be thrown, or any code that specifically catches `IllegalArgumentException` (however unlikely), I have modified the static methods to throw a `IllegalArgumentException` instead?
 
```
public static <T> T validateNotNull(T obj, String errorMsg) {
    if (obj == null)
      throw new IllegalArgumentException(errorMsg);
    return obj;
   }

 public static <T> T validateNotNull(T obj, Supplier<String> errorMsgSupplier) {
    if (obj == null)
      throw new IllegalArgumentException(errorMsgSupplier.get());
    return obj;
  }

```

The alternative is to use the `Objects.requireNonNull` method, catch the `NullPointerException` and then rethrow a IllegalArgumentException. But I believe that's unnecessary.

```
 public static <T> T validateNotNull(T obj, String errorMsg) {
    try {
      Objects.requireNonNull(obj, errorMsg);
    } catch (NullPointerException npe) {
      throw new IllegalArgumentException(npe.getMessage());
    }
    return obj;
  }

  public static <T> T validateNotNull(T obj, Supplier<String> errorMsgSupplier) {
    try {
      Objects.requireNonNull(obj, errorMsgSupplier.get());
    } catch (NullPointerException npe) {
      throw new IllegalArgumentException(npe.getMessage());
    }
    return obj;
  }
```

**Comment by aminburhan** [comment]
> It's very rare (I personally have not seen any) to try and catch `IllegalArgu`

Thank you. I was just drafting a comment on this..

**Comment by aminburhan** [comment]
> > Thanks for your feedback. My apologies for misunderstanding the issue description, where it's clearly stated that a static method should be adopted.
> > I agree with your suggested changes, which will make the code easier to read. I'll implement the changes and see if there's more cases that can be replaced. Thanks!
> 
> Thanks. Another thing to note is that most null check currently throws `IllegalArguementException`. When we start using `Objects.requireNotNull()`, it throws `NullPointException` instead. In theory, if there's any logic that catches `IllegalArguementException` and handles it in some ways, that logic will not work with `NullPointException` anymore since it does not catch it. It's very rare (I personally have not seen any) to try and catch `IllegalArguementException`. Still want to point it out.

Thank you. I was just drafting a comment on this..

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java [hunk 1]
```diff
@@ -127,41 +129,29 @@ private BalancingAction(TopicPartition sourceTp,
   private void validate() {
     switch (_actionType) {
       case REPLICA_ADDITION:
-        if (_destinationBrokerId == null) {
-          throw new IllegalArgumentException("The destination broker cannot be null for balancing action " + this);
-        } else if (_sourceBrokerId != null) {
+        validateNotNull(_destinationBrokerId, "The destination broker cannot be null for balancing action " + this);
```
Comment (Lincong) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java:132]: I think this is exactly the case where the lazy-evaluation `validateNotNull(T obj, Supplier<String> errorMsgSupplier)` method needs to be used since in the previous version, `"The destination broker cannot be null for balancing action " + this` does not get executed unless `_destinationBrokerId == null` is true. So, the change should be:

validateNotNull(_destinationBrokerId, () -> "The destination broker cannot be null for balancing action " + this);

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java [hunk 2]
```diff
@@ -127,41 +129,29 @@ private BalancingAction(TopicPartition sourceTp,
...
           throw new IllegalArgumentException("The source broker should be null for balancing action " + this);
         }
         break;
       case REPLICA_DELETION:
         if (_destinationBrokerId != null) {
           throw new IllegalArgumentException("The destination broker should be null for balancing action " + this);
-        } else if (_sourceBrokerId == null) {
-      throw new IllegalArgumentException("The source broker cannot be null for balancing action " + this);
         }
+        validateNotNull(_sourceBrokerId, "The source broker cannot be null for balancing action " + this);
```
Comment (Lincong) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java:141]: Same issue. Use lazy evaluation.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java [hunk 3]
```diff
@@ -127,41 +129,29 @@ private BalancingAction(TopicPartition sourceTp,
...
         break;
       case INTER_BROKER_REPLICA_MOVEMENT:
       case LEADERSHIP_MOVEMENT:
       case INTER_BROKER_REPLICA_SWAP:
-        if (_destinationBrokerId == null) {
-          throw new IllegalArgumentException("The destination broker cannot be null for balancing action " + this);
-        } else if (_sourceBrokerId == null) {
-          throw new IllegalArgumentException("The source broker cannot be null for balancing action " + this);
-        }
+        validateNotNull(_destinationBrokerId, "The destination broker cannot be null for balancing action " + this);
```
Comment (Lincong) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java:146]: Same issue. Use lazy evaluation.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java [hunk 4]
```diff
@@ -73,15 +75,10 @@ public OptimizationOptions(Set<String> excludedTopics,
...
-    if (excludedTopics == null) {
-      throw new IllegalArgumentException("Excluded topics cannot be null.");
-    } else if (excludedBrokersForLeadership == null) {
-      throw new IllegalArgumentException("Excluded brokers for leadership cannot be null.");
-    } else if (excludedBrokersForReplicaMove == null) {
-      throw new IllegalArgumentException("Excluded brokers for replica move cannot be null.");
-    } else if (requestedDestinationBrokerIds == null) {
-      throw new IllegalArgumentException("Requested destination broker ids cannot be null.");
-    }
+    validateNotNull(excludedTopics, "Excluded topics cannot be null.");
```
Comment (Lincong) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java:78]: Since `validateNotNull ` returns the object if it's not null, you can do:

_excludedTopics = validateNotNull(excludedTopics, "Excluded topics cannot be null.");
_excludedBrokersForLeadership = validateNotNull(excludedBrokersForLeadership, "Excluded brokers for leadership cannot be null.");
...

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyUtils.java [hunk 5]
```diff
@@ -35,10 +36,8 @@ private AnomalyUtils() {
   public static KafkaCruiseControl extractKafkaCruiseControlObjectFromConfig(Map<String, ?> configs,
                                                                             AnomalyType anomalyType) {
     KafkaCruiseControl kafkaCruiseControl = (KafkaCruiseControl) configs.get(KAFKA_CRUISE_CONTROL_OBJECT_CONFIG);
-    if (kafkaCruiseControl == null) {
-      throw new IllegalArgumentException(String.format("Missing %s when creating anomaly of type %s.",
-                                                       KAFKA_CRUISE_CONTROL_OBJECT_CONFIG, anomalyType));
-    }
+    validateNotNull(kafkaCruiseControl, String.format("Missing %s when creating anomaly of type %s.",
```
Comment (Lincong) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyUtils.java:39]: We can do `return validateNotNull(...)`

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java [hunk 6]
```diff
@@ -739,12 +740,8 @@ public synchronized void setGeneratingProposalsForExecution(String uuid, Supplie
     if (currentExecutorState != NO_TASK_IN_PROGRESS) {
       throw new OngoingExecutionException(String.format("Cannot generate proposals while the executor is in %s state.", currentExecutorState));
     }
-    if (uuid == null) {
-      throw new IllegalArgumentException("UUID of the execution cannot be null.");
-    }
-    if (reasonSupplier == null) {
-      throw new IllegalArgumentException("Reason supplier cannot be null.");
-    }
+    validateNotNull(uuid, "UUID of the execution cannot be null.");
```
Comment (Lincong) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java:743]: Same issue: `_uuid  = validateNotNull(uuid, "UUID of the execution cannot be null.");`

**Review by Lincong — CHANGES_REQUESTED** [review]
There are 2 things to improve.

1. Use lazy evaluation when the error message is dynamically generated
2. Use the return value from the `validateNotNull` directly

Could you please fix all cases to which the above two issues apply? Thanks!

**Comment by aminburhan** [comment]
> There are 2 things to improve.
> 
> 1. Use lazy evaluation when the error message is dynamically generated
> 2. Use the return value from the `validateNotNull` directly
> 
> Could you please fix all cases to which the above two issues apply? Thanks!

I have implemented the suggested improvements. 

There are more cases that can be replaced, however these null checks throws other types of exceptions.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java [hunk 7]
```diff
@@ -354,11 +355,9 @@ public static void sanityCheckOfflineReplicaPresence(ClusterModel clusterModel)
     private final Set<Integer> _recentlyDemotedBrokers;
 
     public RecentBrokers(Set<Integer> recentlyRemovedBrokers, Set<Integer> recentlyDemotedBrokers) {
-      if (recentlyRemovedBrokers == null || recentlyDemotedBrokers == null) {
-        throw new IllegalArgumentException("Attempt to set a null value for recent brokers.");
-      }
-      _recentlyRemovedBrokers = recentlyRemovedBrokers;
-      _recentlyDemotedBrokers = recentlyDemotedBrokers;
+      String errorMsg = "Attempt to set a null value for recent brokers.";
```
Comment (Lincong) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java:358]: Instead of reusing the error message, I think we can be more specific by:

```
_recentlyRemovedBrokers = validateNotNull(recentlyRemovedBrokers, "Attempt to set a null value for recent removed brokers.");
_recentlyDemotedBrokers = validateNotNull(recentlyDemotedBrokers, "Attempt to set a null value for recent demoted brokers.");
```

**Review by Lincong — CHANGES_REQUESTED** [review]
One last nit issue

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java (hunk 7 above)
Comment (aminburhan) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java]: Thanks for your input. I've made the error message more specific.

**Review by Lincong — APPROVED** [review]
LGTM. Thanks for your PR

**Comment by aminburhan** [comment]
> LGTM. Thanks for your PR. Could you please squash and merge this PR to master after modifying the commit message to reflect the actual change. The current commit message `Converts traditional null checks to use Objects.requireNonNull` is not accurate.

I don't have write access to this repository.

**Comment by Lincong** [comment]
> > LGTM. Thanks for your PR. Could you please squash and merge this PR to master after modifying the commit message to reflect the actual change. The current commit message `Converts traditional null checks to use Objects.requireNonNull` is not accurate.
> 
> I don't have write access to this repository.

I just merged it to master. Thanks for your contribution!
