### PR TITLE
Skip parsing scopes that have keys without a matching value.

### LINKED ISSUE #1296: Unable to publish Cruise Control Metrics in Confluent Platform 5.3.1
First time trying to get Cruise Control up and running in a three node Confluent Platform 5.3 Kafka cluster using mutual TLS auth.   I followed the instructions at https://github.com/linkedin/cruise-control/blob/master/README.md and I'm currently running into an issue where according to my Kafka logs I'm not able to send Cruise Control metrics.  Here's a sample of the log messages I'm seeing

```
[2020-08-02 20:43:02,318] WARN Failed to send Cruise Control metric [BROKER_METRIC,BROKER_FOLLOWER_FETCH_REQUEST_QUEUE_TIME_MS_MEAN,time=1596416882261,brokerId=1002,value=0.128] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
```

My server.prpoerties looks like this (some values are redacted)
```
advertised.listeners=TRUSTED://mybroker:9093
authorizer.class.name=io.confluent.kafka.security.ldap.authorizer.LdapAuthorizer
auto.create.topics.enable=false
broker.id.generation.enable=true
confluent.metrics.reporter.bootstrap.servers=mybrokerlist
confluent.metrics.reporter.security.protocol=SSL
confluent.metrics.reporter.ssl.keystore.location=/etc/ssl/kafka.server.keystore.jks
confluent.metrics.reporter.ssl.keystore.password=somepassword
confluent.metrics.reporter.ssl.truststore.location=/etc/ssl/kafka.server.truststore.jks
confluent.metrics.reporter.ssl.truststore.password=somepassword
confluent.metrics.reporter.topic.replicas=3
confluent.support.metrics.enable=true
group.initial.rebalance.delay.ms=3
inter.broker.listener.name=TRUSTED
ldap.authorizer.group.member.attribute.pattern=[Cc][Nn]=([^,]*),.*
ldap.authorizer.group.object.class=group
ldap.authorizer.group.search.base=myous
ldap.authorizer.group.search.scope=2
ldap.authorizer.java.naming.provider.url=ldaps://someadserver:636
ldap.authorizer.java.naming.security.authentication=SIMPLE
ldap.authorizer.java.naming.security.credentials=somecredentials
ldap.authorizer.java.naming.security.principal=someuserinad
ldap.authorizer.java.naming.security.protocol=SSL
ldap.authorizer.license=mylicensestring
ldap.authorizer.refresh.interval.ms=60000
ldap.authorizer.ssl.truststore.location=/etc/ssl/kafka.server.truststore.jks
ldap.authorizer.ssl.truststore.password=somepassword
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,TRUSTED:SSL
listeners=TRUSTED://:9093
log.dirs=/data/kafka_data/kafka-logs
log.retention.check.interval.ms=300000
log.retention.hours=168
log.segment.bytes=1073741824
metric.reporters=io.confluent.metrics.reporter.ConfluentMetricsReporter,com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
num.io.threads=8
num.network.threads=3
num.partitions=10
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=3
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
socket.send.buffer.bytes=102400
ssl.client.auth=requested
ssl.keystore.location=/etc/ssl/kafka.server.keystore.jks
ssl.keystore.password=somepassword
ssl.principal.mapping.rules=RULE:^.*[Cc][Nn]=(.*).q2dc.local.*$/$1/,RULE:^.*[Cc][Nn]=([a-zA-Z0-9 -]*).*$/$1/,DEFAULT
ssl.truststore.location=/etc/ssl/kafka.server.truststore.jks
ssl.truststore.password=somepassword
super.users=someusers
Group:somegroup
transaction.state.log.min.isr=2
transaction.state.log.replication.factor=3
zookeeper.connect=somezookeeperhosts
zookeeper.connection.timeout.ms=6000
cruise.control.metrics.reporter.ssl.truststore.location=/etc/ssl/kafka.server.truststore.jks
cruise.control.metrics.reporter.ssl.truststore.password=somepassword
cruise.control.metrics.reporter.ssl.keystore.location=/etc/ssl/kafka.server.keystore.jks
cruise.control.metrics.reporter.ssl.keystore.password=somepassword
cruise.control.metrics.reporter.bootstrap.servers=mybrokerlist
```

Cruise Control jar file location
```
# ls -al /usr/share/java/kafka/cruise-control-metrics-reporter-2.0.122.jar
-rw-r--r-- 1 root root 47151 Jul 29 08:55 /usr/share/java/kafka/cruise-control-metrics-reporter-2.0.122.jar
```

Cruise Control Topic
```
Topic:__CruiseControlMetrics    PartitionCount:10       ReplicationFactor:1     Configs:min.insync.replicas=1,cleanup.policy=delete,segment.bytes=1073741824,retention.ms=604800000,max.message.bytes=1000012,retention.bytes=-1,delete.retention.ms=86400000
        Topic: __CruiseControlMetrics   Partition: 0    Leader: 1001    Replicas: 1001  Isr: 1001
        Topic: __CruiseControlMetrics   Partition: 1    Leader: 1003    Replicas: 1003  Isr: 1003
        Topic: __CruiseControlMetrics   Partition: 2    Leader: 1001    Replicas: 1001  Isr: 1001
        Topic: __CruiseControlMetrics   Partition: 3    Leader: 1003    Replicas: 1003  Isr: 1003
        Topic: __CruiseControlMetrics   Partition: 4    Leader: 1001    Replicas: 1001  Isr: 1001
        Topic: __CruiseControlMetrics   Partition: 5    Leader: 1003    Replicas: 1003  Isr: 1003
        Topic: __CruiseControlMetrics   Partition: 6    Leader: 1001    Replicas: 1001  Isr: 1001
        Topic: __CruiseControlMetrics   Partition: 7    Leader: 1003    Replicas: 1003  Isr: 1003
        Topic: __CruiseControlMetrics   Partition: 8    Leader: 1001    Replicas: 1001  Isr: 1001
        Topic: __CruiseControlMetrics   Partition: 9    Leader: 1003    Replicas: 1003  Isr: 1003
```

Any help in figuring out what's preventing me from publishing metrics will be greatly appreciated.

### PR DESCRIPTION
**Pull request by efeg**
This PR resolves #1296.
-- also note that `assert` statement is removed as (1) it is typically not enabled anyway (i.e. unless users explicitly use the `-ea` switch, it is disabled) and (2) this makes metrics reporter more defensive against Yammer metrics with an unexpected scope.

### CODE REVIEW

File: cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java [hunk 1]
```diff
@@ -204,11 +204,15 @@ public static boolean isInterested(com.yammer.metrics.core.MetricName metricName
...
    * Convert a yammer metrics scope to a tags map.
+   * Skip parsing scopes that (1) are {@code null} or (2) have keys without a matching value
+   * (see https://github.com/linkedin/cruise-control/issues/1296).
    */
   private static Map<String, String> yammerMetricScopeToTags(String scope) {
     if (scope != null) {
       String[] kv = scope.split("\\.");
-      assert kv.length % 2 == 0;
+      if (kv.length % 2 != 0) {
+        return Collections.emptyMap();
```
Comment (smccauliff) [inline cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java:214]: Do you know if it's safe to ignore generating the map for these metrics?

**Review by smccauliff — APPROVED** [review]
Doing additional logging here is probably too expensive so I don't have any objections.

File: cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java (hunk 1 above)
Comment (efeg) [reply cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java:214]: This util function helps with the identification of whether given Kafka Yammer metrics are of interest to CC metrics reporter or not. The Kafka code ensures that `scope` is either a KV pair separated by a dot or `null` (see [relevant code](https://github.com/apache/kafka/blob/7e1c39f75abc443281f31f3c2f1e4829e738619d/core/src/main/scala/kafka/metrics/KafkaMetricsGroup.scala#L91)). Hence, unless these assumptions are broken, this should be safe.

However, in the unlikely scenario, where scope of Yammer metrics contains an odd number of elements, generating an empty map here may lead to a false positive -- i.e. the Yammer metric can be mistakenly identified as one of the metrics that CC metrics reporter is interested in. To prevent this scenario, I updated the handling logic for `kv.length % 2 != 0` case in `yammerMetricScopeToTags` to return `null` (to indicate `unacceptable` scope) and the callers of this util function to take a note of this response to avoid misidentification of tags.
