### PR TITLE
Prevent ResourceDistributionGoal from generating provision recommendations with a negative number of brokers to remove.

### LINKED ISSUE #1513: Prevent ResourceDistributionGoal from generating provision recommendations with a negative number of brokers to remove
In heterogeneous clusters with brokers having different resource capacities, `ResourceDistributionGoal` may generate provision recommendations with a negative number of brokers to remove. This causes the optimization to fail with an `IllegalArgumentException` such as the following:

```
Error processing POST request '/rebalance' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.IllegalArgumentException: Number of brokers must be positive (-176).'
```

Ensure that the ResourceDistributionGoal does not generate provision recommendations with a negative number of brokers to remove.

### PR DESCRIPTION
**Pull request by efeg**
This PR resolves #1513.

### CODE REVIEW

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java [hunk 1]
```diff
@@ -268,18 +268,35 @@ protected void initGoalState(ClusterModel clusterModel, OptimizationOptions opti
...
+      // To make sure that the recommended brokers to drop in an heterogeneous cluster is a positive number, the typical broker must have
+      // the max capacity.
+      int typicalBrokerId = brokerIdWithMaxCapacity(clusterModel);
       double typicalCapacity = clusterModel.broker(typicalBrokerId).capacityFor(resource());
 
       // Any capacity greater than the allowed capacity may yield over-provisioning.
       double allowedCapacity = resourceUtilization / _balancingConstraint.lowUtilizationThreshold(resource());
       int allowedNumBrokers = (int) (allowedCapacity / typicalCapacity);
-      int numBrokersToDrop = _brokersAllowedReplicaMove.size() - allowedNumBrokers;
+      int numBrokersToDrop = Math.max(_brokersAllowedReplicaMove.size() - allowedNumBrokers, 1);
```
Comment (bachmanity1) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java:279]: @efeg 

What if `_brokersAllowedReplicaMove.size()`  equals `allowedNumBrokers`? Wouldn't this suggest removing a broker even when cluster size doesn't need any change?

Wouldn't it be safer to make this line look like this? 

```java
int numBrokersToDrop = Math.max(_brokersAllowedReplicaMove.size() - allowedNumBrokers, 0);
```
