### PR TITLE
Handle non-existent topic while setting/removing throttled replicas for a topic

### LINKED ISSUE #1318: Deleted topic shouldn't stop the executor
Hi, 
While running Cruise Control for the first time, a topic that was part of a reassignment got deleted, making the executor stop the current rebalance. 

```
[2020-08-31 14:09:38] ERROR ProposalExecutor-0 Executor:1028 - Executor got exception during execution
kafka.admin.AdminOperationException: Topic "topic_name_here" does not exist.
	at kafka.zk.AdminZkClient.validateTopicConfig(AdminZkClient.scala:326)
	at kafka.zk.AdminZkClient.changeTopicConfig(AdminZkClient.scala:340)
	at com.linkedin.kafka.cruisecontrol.executor.ExecutorUtils$.changeTopicConfig(ExecutorUtils.scala:133)
	at com.linkedin.kafka.cruisecontrol.executor.ExecutorUtils.changeTopicConfig(ExecutorUtils.scala)
	at com.linkedin.kafka.cruisecontrol.executor.ReplicationThrottleHelper.setThrottledReplicas(ReplicationThrottleHelper.java:185)
	at com.linkedin.kafka.cruisecontrol.executor.ReplicationThrottleHelper.setLeaderThrottledReplicas(ReplicationThrottleHelper.java:168)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.linkedin.kafka.cruisecontrol.executor.ReplicationThrottleHelper.setThrottles(ReplicationThrottleHelper.java:54)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.interBrokerMoveReplicas(Executor.java:1156)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.execute(Executor.java:985)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.run(Executor.java:911)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-08-31 14:09:38] WARN  ProposalExecutor-0 operationLogger:1063 - Task [fde0e0e0-698a-4720-ac31-da31e5ac377e] userPOST /kafkacruisecontrol/REBALANCE execution is interrupted with exception Topic "topic_name_here" does not exist..
[2020-08-31 14:09:38] INFO  ProposalExecutor-0 Executor:912 - Execution finished.
```

Wouldn't be beneficial if the executor just skipped this topic and continue the rebalance tasks instead of stopping it ? 
Thanks in advance !

### PR DESCRIPTION
**Pull request by Lincong**
This PR resolves #1318.

### CODE REVIEW

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java [hunk 1]
```diff
@@ -260,12 +287,16 @@ private boolean removeFollowerThrottledReplicasFromTopic(Properties config, Stri
   }
 
   private void removeThrottledReplicasFromTopic(String topic, Set<String> replicas) {
-    Properties config = _kafkaZkClient.getEntityConfigs(ConfigType.Topic(), topic);
-    boolean removedLeaderThrottle = removeLeaderThrottledReplicasFromTopic(config, topic, replicas);
-    boolean removedFollowerThrottle = removeFollowerThrottledReplicasFromTopic(config, topic, replicas);
+    Properties topicConfigs = _kafkaZkClient.getEntityConfigs(ConfigType.Topic(), topic);
+    if (topicConfigs == null || topicConfigs.isEmpty()) {
+      LOG.warn("Skip removing throttled replicas {} from topic {} since no configs can be read", String.join(",", replicas), topic);
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java:292]: When would this be expected to happen? 
Here are some scenarios that I can think of:
  (1) a topic is deleted and then shortly after recreated with the same name with no config,
  (2) someone externally overrides the configs,
  (3) a programming error

If it happens due to (1) or (2), are users expected to do anything if they see this warning log? Does the way we handle it suffice to provide the right behavior?
Assuming that we have proper testing so that (3) is unlikely, should we make this a `debug` level log so that we don't cause extra logs that are not actionable?

File: cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java [hunk 2]
```diff
@@ -101,6 +101,57 @@ public void testIsNoOpWhenThrottleIsNull() {
...
+    EasyMock.expect(mockKafkaZkClient.topicExists(TOPIC0)).andReturn(false).times(4);
+    EasyMock.replay(mockKafkaZkClient);
+
+    throttleHelper.setThrottles(Collections.singletonList(proposal));
+    EasyMock.verify(mockKafkaZkClient);
+  }
+
+  private void prepareKafkaZkClientMockWithBrokerConfigs(KafkaZkClient mockKafkaZkClient) {
+    // All participating brokers have throttled rate set already
+    Properties brokerThrottledRateProps = new Properties();
```
Comment (efeg) [inline cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java:146]: Nit: ... -> `new Properties(2);`?

File: cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java [hunk 3]
```diff
@@ -101,6 +101,57 @@ public void testIsNoOpWhenThrottleIsNull() {
...
+    EasyMock.replay(mockKafkaZkClient);
+    ReplicationThrottleHelper throttleHelper = new ReplicationThrottleHelper(mockKafkaZkClient, throttleRate);
+
+    throttleHelper.setThrottles(Collections.singletonList(proposal));
+    EasyMock.verify(mockKafkaZkClient);
+
+    // Case 2: a situation where Topic0 gets deleted after its configs were read. Change configs should not fail.
+    EasyMock.reset(mockKafkaZkClient);
+    prepareKafkaZkClientMockWithBrokerConfigs(mockKafkaZkClient);
+    Properties topicConfigProps = new Properties();
```
Comment (efeg) [inline cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java:132]: Nit: ... -> `new Properties(2);`?

File: cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java [hunk 4]
```diff
@@ -101,6 +101,57 @@ public void testIsNoOpWhenThrottleIsNull() {
...
+    String throttledReplicas = brokerId0 + "," + brokerId1;
+    topicConfigProps.put(ReplicationThrottleHelper.LEADER_THROTTLED_REPLICAS, throttledReplicas);
+    topicConfigProps.put(ReplicationThrottleHelper.FOLLOWER_THROTTLED_REPLICAS, throttledReplicas);
+    EasyMock.expect(mockKafkaZkClient.getEntityConfigs(ConfigType.Topic(), TOPIC0)).andReturn(topicConfigProps).times(2);
+    EasyMock.expect(mockKafkaZkClient.topicExists(TOPIC0)).andReturn(false).times(4);
+    EasyMock.replay(mockKafkaZkClient);
+
+    throttleHelper.setThrottles(Collections.singletonList(proposal));
```
Comment (efeg) [inline cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java:140]: Should we test the changes in `removeThrottledReplicasFromTopic`, too?

**Review by efeg — CHANGES_REQUESTED** [review]
Thanks for the patch! Left some comments

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java [hunk 5]
```diff
@@ -260,12 +287,16 @@ private boolean removeFollowerThrottledReplicasFromTopic(Properties config, Stri
   }
 
   private void removeThrottledReplicasFromTopic(String topic, Set<String> replicas) {
-    Properties config = _kafkaZkClient.getEntityConfigs(ConfigType.Topic(), topic);
-    boolean removedLeaderThrottle = removeLeaderThrottledReplicasFromTopic(config, topic, replicas);
-    boolean removedFollowerThrottle = removeFollowerThrottledReplicasFromTopic(config, topic, replicas);
+    Properties topicConfigs = _kafkaZkClient.getEntityConfigs(ConfigType.Topic(), topic);
+    if (topicConfigs == null || topicConfigs.isEmpty()) {
```
[the remark this answers is not in the document]
Comment (Lincong) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java:291]: The current implementation of the `getEntityConfigs` method does not return `null`. However, it's not safe to assume it will never return `null`. We can assume it will not return null only if the API clearly claims its behavior.

File: cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java (hunk 3 above)
Comment (Lincong) [reply cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java:132]: I don't think `java.util. Properties` class has a constructor that takes a size parameter.

File: cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java (hunk 2 above)
Comment (Lincong) [reply cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java:146]: I don't think java.util. Properties class has a constructor that takes a size parameter.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java [hunk 6]
```diff
@@ -189,8 +198,26 @@ private void setThrottledReplicas(String topic, Set<String> replicas, boolean th
...
+  /**
+   * Update topic configuration properties if a topic exist. No-op for non-existent topic
+   *
+   * @param topicName topic name
+   * @param topicConfigs configuration properties to update
+   */
+  private void changeTopicConfigs(String topicName, Properties topicConfigs) {
+    try {
+      ExecutorUtils.changeTopicConfig(_adminZkClient, topicName, topicConfigs);
+    } catch (Exception e) {
```
[the remark this answers is not in the document]
Comment (Lincong) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java:214]: The `AdminZkClient.changeTopicConfig` API does not claim that it might throw `AdminOperationException`. Even though we know that is the kind of exception it might throw, we should not make this assumption unless it's part of the public contract.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java (hunk 1 above)
Comment (Lincong) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java:292]: OK, I agree that we can change it to `debug` level

File: cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java (hunk 4 above)
Comment (Lincong) [reply cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java:140]: Yes, test added

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java [hunk 7]
```diff
@@ -176,9 +176,18 @@ private void setFollowerThrottledReplicas(String topic, Set<String> replicas) {
...
+    if (topicConfigs == null || topicConfigs.isEmpty()) {
+      // Not assume that no topic config means means topic does not exist. Always check topic existence in this situation
+      if (!_kafkaZkClient.topicExists(topic)) {
+        LOG.debug("Skip setting throttled replicas {} for topic {} since topic does not exist", String.join(",", replicas), topic);
+        return;
+      }
+      if (topicConfigs == null) {
+        topicConfigs = new Properties();
+      }
+    }
```
[the remark this answers is not in the document]
Comment (Lincong) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java]: 1. It's safer to assume `getEntityConfigs` might return `null` since it does not claim it never returns null as its public contract
2. You are right. No need to check the topic existence here.
3. Fixed

File: cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java (hunk 2 above)
Comment (efeg) [reply cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java]: It does in Java 11 -- but it is fine to keep it as is for supporting Java 8+. https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Properties.html#%3Cinit%3E(int)

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (efeg) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java]: -- Discussed offline.
We will keep the existing logic because API contract leaves the behavior unspecified and the implementation does not return `null`. Hence, we cannot assume that if a future version happens to start returning `null` it would imply that the topic does not exist (i.e. it can return null for some other irrelevant reason). Thus, It is safer to fail if a behavior change causes a `null` response.

**Review by efeg — APPROVED** [review]
Thanks for the updates -- LGTM.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java [hunk 8]
```diff
@@ -260,27 +277,31 @@ private boolean removeFollowerThrottledReplicasFromTopic(Properties config, Stri
   }
 
   private void removeThrottledReplicasFromTopic(String topic, Set<String> replicas) {
-    Properties config = _kafkaZkClient.getEntityConfigs(ConfigType.Topic(), topic);
-    boolean removedLeaderThrottle = removeLeaderThrottledReplicasFromTopic(config, topic, replicas);
-    boolean removedFollowerThrottle = removeFollowerThrottledReplicasFromTopic(config, topic, replicas);
+    Properties topicConfigs = _kafkaZkClient.getEntityConfigs(ConfigType.Topic(), topic);
+    if (topicConfigs.isEmpty()) {
```
Comment (jiao-zhangS) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java:281]: Question: should also call "_kafkaZkClient.isTopicMarkedForDeletion()" to exclude the topic that is marked as deletion? @Lincong
