### PR TITLE
Make the retrieval of the desired replication factor of sample store topics more robust

### LINKED ISSUE #1829: Make more robust the retrieve of the desired replication factor of sample store topics
Cruise Control is rarely fails due to one of the following issues:
- "Auto creation of sample store topics failed due to failure to describe cluster."
- "Kafka cluster has less than 2 brokers (brokers in cluster=%d, zookeeper.connect=%s)"

This happen when the goal is to retrieve the desired replication factor of sample store topics. This can be more robust if a retry mechanizm is introduced.

### PR DESCRIPTION
**Pull request by egyedt**
This PR resolves #1829.

### CODE REVIEW

**Comment by egyedt** [comment]
@efeg 
Could you please review this change?

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java [hunk 1]
```diff
@@ -63,23 +63,43 @@ protected void createProducer(Map<String, ?> config, String producerClientId) {
...
+          throw new IllegalStateException("Auto creation of sample store topics failed due to failure to describe cluster.", e);
+        }
+        if (numberOfBrokersInCluster <= 1) {
+          throw new IllegalStateException(String.format("Kafka cluster has less than 2 brokers (brokers in cluster=%d, zookeeper.connect=%s)",
+                  numberOfBrokersInCluster, config.get(ExecutorConfig.ZOOKEEPER_CONNECT_CONFIG)));
+        }
+
+        return (short) Math.min(DEFAULT_SAMPLE_STORE_TOPIC_REPLICATION_FACTOR, numberOfBrokersInCluster);
+      } catch (IllegalStateException e) {
+        if (retryCount + 1 == maxRetryCount) {
```
Comment (CCisGG) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:90]: nit: I think it makes more sense to make it:

`if (retryCount == maxRetryCount)`

And then in line 75, it should be:

`while (retryCount <= maxRetryCount)`

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java [hunk 2]
```diff
@@ -63,23 +63,43 @@ protected void createProducer(Map<String, ?> config, String producerClientId) {
...
-      return (short) Math.min(DEFAULT_SAMPLE_STORE_TOPIC_REPLICATION_FACTOR, numberOfBrokersInCluster);
+      retryCount++;
+      try {
+        TimeUnit.MILLISECONDS.sleep(waitingTime);
+      } catch (InterruptedException ignored) {
+      }
     }
 
-    return _sampleStoreTopicReplicationFactor;
+    return (short) Math.min(DEFAULT_SAMPLE_STORE_TOPIC_REPLICATION_FACTOR, numberOfBrokersInCluster);
```
Comment (CCisGG) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:102]: Would the code execution ever reach this line? If not, we should just throw an exception here.

**Review by CCisGG — CHANGES_REQUESTED** [review]
Code looks almost good to me. Could you try to add some unit test for this change?

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java (hunk 1 above)
Comment (egyedt) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:90]: OK, thank you for your advice.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java (hunk 2 above)
Comment (egyedt) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:102]: No, this line is unreachable. OK, I will throw an exception here.

**Comment by egyedt** [comment]
@CCisGG 
I made the requested changes.
Could you please review my PR again?

**Review by CCisGG — APPROVED** [review]
Changes look good to me. Thanks @egyedt !

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java [hunk 3]
```diff
@@ -278,6 +278,20 @@ public final class MonitorConfig {
...
+   * <code>fetch.metric.samples.retry.count</code>
+   */
+  public static final String FETCH_METRIC_SAMPLES_RETRY_COUNT_CONFIG = "fetch.metric.samples.retry.count";
+  public static final int DEFAULT_FETCH_METRIC_SAMPLES_RETRY_COUNT = 5;
+  public static final String FETCH_METRIC_SAMPLES_RETRY_COUNT_DOC = "The maximum number of retries during the fetch of metric samples.";
+
+  /**
+   * <code>fetch.metric.samples.retry.waiting.ms</code>
+   */
+  public static final String FETCH_METRIC_SAMPLES_WAITING_MS_CONFIG = "fetch.metric.samples.retry.waiting.ms";
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java:291]: Can we update `Configurations.md` to document these configs in the wiki?
That being said, `FETCH_METRIC_SAMPLES_WAITING_MS_CONFIG` might be redundant -- please see the other comments regarding code reuse.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java [hunk 4]
```diff
@@ -63,23 +63,44 @@ protected void createProducer(Map<String, ?> config, String producerClientId) {
...
+        if (numberOfBrokersInCluster <= 1) {
+          throw new IllegalStateException(String.format("Kafka cluster has less than 2 brokers (brokers in cluster=%d, zookeeper.connect=%s)",
+                  numberOfBrokersInCluster, config.get(ExecutorConfig.ZOOKEEPER_CONNECT_CONFIG)));
+        }
+
+        return (short) Math.min(DEFAULT_SAMPLE_STORE_TOPIC_REPLICATION_FACTOR, numberOfBrokersInCluster);
+      } catch (IllegalStateException e) {
+        if (retryCount == maxRetryCount) {
+          throw e;
+        }
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:93]: This retry logic keeps retrying if `numberOfBrokersInCluster <= 1`. What is the intention of retry if the cluster has less than or equal to 1 broker? Do we expect the number of alive nodes in the cluster to increase between retries?

Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:93]: Would it possible to use the existing `CruiseControlMetricsUtils#retry` rather than reintroducing a new retry logic here?

**Review by efeg — CHANGES_REQUESTED** [review]
Thanks for the PR -- Left some comments.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java (hunk 4 above)
Comment (egyedt) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:93]: Yes, it may happen (rarely) with Kafka, that brokers initialization is too slow. If the CC started too and this line of code is reached during the init of the Kafka then this exception could happen. This failure can prevent with this retry mechanizm since further couple of seconds/mins could be enough to the Kafka brokers to be available.

Comment (egyedt) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractKafkaSampleStore.java:93]: Thanks for your advice.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java (hunk 3 above)
Comment (egyedt) [reply cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java:291]: Yes, thank you for this reminder!

**Comment by egyedt** [comment]
@efeg 
Thank you for your suggestions. I made the requested changes.
Could you please review my PR again?

File: docs/wiki/User Guide/Configurations.md [hunk 5]
```diff
@@ -85,6 +85,8 @@ The following configurations are inherited from the open source Kafka client con
...
+| fetch.metric.samples.retry.count                              | Integer | N         | 5                                                                                       | The maximum number of retries during the fetch of metric samples.                                                                                                                                                                                                                                                                                                                                                   |
+| fetch.metric.samples.retry.waiting.ms                         | Long    | N         | 30                                                                                      | The milliseconds between two retries during the fetch of metric samples.                                                                                                                                                                                                                                                                                                                                            |
```
Comment (efeg) [inline docs/wiki/User Guide/Configurations.md:89]: Please see earlier comment regarding dropping this config.

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java [hunk 6]
```diff
@@ -278,6 +278,20 @@ public final class MonitorConfig {
   public static final String LINEAR_REGRESSION_MODEL_MIN_NUM_CPU_UTIL_BUCKETS_DOC = "The minimum number of full CPU"
       + " utilization buckets required to generate a linear regression model.";
 
+  /**
+   * <code>fetch.metric.samples.retry.count</code>
+   */
+  public static final String FETCH_METRIC_SAMPLES_RETRY_COUNT_CONFIG = "fetch.metric.samples.retry.count";
+  public static final int DEFAULT_FETCH_METRIC_SAMPLES_RETRY_COUNT = 5;
+  public static final String FETCH_METRIC_SAMPLES_RETRY_COUNT_DOC = "The maximum number of retries during the fetch of metric samples.";
```
Comment (efeg) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java:286]: The name and description of this config does not seem accurate. Isn't this config about the maximum number of retries to identify the sample store topic replication factor?

File: docs/wiki/User Guide/Configurations.md [hunk 7]
```diff
@@ -85,6 +85,8 @@ The following configurations are inherited from the open source Kafka client con
...
 | broker.metric.sample.aggregator.completeness.cache.size       | Integer | N         | 5                                                                                       | The metric sample aggregator caches the completeness metadata for fast query. The completeness describes the confidence level of the data in the metric sample aggregator. It is primarily measured by the validity of the metrics samples in different windows. This configuration configures The number of completeness cache slots to maintain.                                                                  |
+| fetch.metric.samples.retry.count                              | Integer | N         | 5                                                                                       | The maximum number of retries during the fetch of metric samples.                                                                                                                                                                                                                                                                                                                                                   |
```
Comment (efeg) [inline docs/wiki/User Guide/Configurations.md:88]: Please see comment on config name and description

File: build.gradle [hunk 8]
```diff
@@ -292,6 +292,8 @@ project(':cruise-control') {
     testImplementation 'org.bouncycastle:bcpkix-jdk15on:1.70'
     testImplementation 'org.apache.kerby:kerb-simplekdc:2.0.1'
     testImplementation 'com.jayway.jsonpath:json-path:2.7.0'
+    testImplementation 'org.powermock:powermock-module-junit4:2.0.9'
+    testImplementation 'org.powermock:powermock-api-mockito2:2.0.9'
```
Comment (efeg) [inline build.gradle:296]: CC has been using easymock rather than mockito. Can we use the following dependency here -- and do the necessary updates on the test code to use easymock rather than mockito:
```
testImplementation 'org.powermock:powermock-api-easymock:2.0.9'
```

**Review by efeg — COMMENTED** [review]
@egyedt Thanks for the updates -- left some comments.

**Comment by egyedt** [comment]
@efeg
Thank you for your suggestions.
Could you please review this PR again?

**Comment by egyedt** [comment]
@efeg 
Could we close/merge this PR if everything looks good?

File: cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java [hunk 9]
```diff
@@ -278,6 +278,14 @@ public final class MonitorConfig {
   public static final String LINEAR_REGRESSION_MODEL_MIN_NUM_CPU_UTIL_BUCKETS_DOC = "The minimum number of full CPU"
       + " utilization buckets required to generate a linear regression model.";
 
+  /**
+   * <code>fetch.metric.samples.retry.count.max</code>
+   */
+  public static final String FETCH_METRIC_SAMPLES_RETRY_COUNT_MAX_CONFIG = "fetch.metric.samples.retry.count.max";
```
Comment (CCisGG) [inline cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java:284]: Nit: from the other config naming convention, it seems "fetch.metric.samples.max.retry.count" is a better config name. Can we change that?

**Comment by CCisGG** [comment]
Thanks @egyedt! The update looks good to me in general, and I left one more last nit.

**Comment by egyedt** [comment]
@efeg, @CCisGG 
Thank you for your reviews.
Could you please merge this PR if everything OK now?

**Comment by CCisGG** [comment]
Merged. Thanks @egyedt !
