### PR TITLE
Handle missing listeners config in CruiseControlMetricsReporter

### LINKED ISSUE #1430: Fatal error during KafkaServer startup at CruiseControlMetricsReporter.getBootstrapServers...
when KafkaServer listeners config is omitted. By default listeners config was commented out.

### To reproduce
1. Follow cruise-control quick-start to download Kafka 2.7
2. Append `metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter` to `config/server.properties`
3. `$ cd kafka_2.13-2.7.0 ; bin/kafka-server-start.sh config/server.properties`
Output:
```
...
[2020-12-23 15:30:09,806] INFO [ExpirationReaper-0-AlterAcls]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2020-12-23 15:30:09,823] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.getBootstrapServers(CruiseControlMetricsReporter.java:127)
        at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(CruiseControlMetricsReporter.java:139)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:390)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:450)
        at kafka.server.DynamicMetricsReporters.createReporters(DynamicBrokerConfig.scala:794)
        at kafka.server.DynamicMetricsReporters.<init>(DynamicBrokerConfig.scala:743)
        at kafka.server.DynamicBrokerConfig.addReconfigurables(DynamicBrokerConfig.scala:248)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:375)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
        at kafka.Kafka$.main(Kafka.scala:82)
        at kafka.Kafka.main(Kafka.scala)
[2020-12-23 15:30:09,826] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2020-12-23 15:30:09,827] INFO [SocketServer brokerId=0] Stopping socket server request processors (kafka.network.SocketServer)...```

### PR DESCRIPTION
**Pull request by efeg**
This PR resolves #1430.

### CODE REVIEW

**Review by zornhsu — APPROVED** [review]
LGTM. Thanks for the PR.

File: cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java [hunk 1]
```diff
@@ -116,7 +116,7 @@ public void close() {
   static String getBootstrapServers(Map<String, ?> configs) {
     Object port = configs.get(KafkaConfig.PortProp());
     String listeners = String.valueOf(configs.get(KafkaConfig.ListenersProp()));
-    if (listeners != null && listeners.length() != 0) {
+    if (!listeners.equals("null") && listeners.length() != 0) {
```
Comment (Lincong) [inline cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java:119]: Since this change is not backward compatible in a way that it does not handle the `listeners == null` case. So, is  `listeners` guaranteed never to be null?

**Review by Lincong — CHANGES_REQUESTED** [review]

File: cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java (hunk 1 above)
Comment (efeg) [reply cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java:119]: Correct, `String.valueOf(...)` does not return `null`, but can return `"null"`

Comment (Lincong) [reply cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java:119]: I see. Thanks

**Review by Lincong — APPROVED** [review]
